# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('parcel', models.CharField(blank=True, max_length=255)),
                ('folder_num', models.CharField(blank=True, max_length=255)),
                ('folder_desc', models.CharField(blank=True, max_length=255)),
                ('folder_name', models.CharField(blank=True, max_length=255)),
                ('approvals', models.CharField(blank=True, max_length=255)),
                ('issued', models.DateField()),
                ('dwelling_units', models.FloatField(default=0.0)),
                ('valuation', models.FloatField(default=0.0)),
                ('square_footage', models.FloatField(default=0.0)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permits_applied_for', to='mapview.Entity')),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permits_worked', to='mapview.Entity')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permits_on_owned', to='mapview.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='permit',
            name='subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapview.SubType'),
        ),
        migrations.AddField(
            model_name='permit',
            name='work_desc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapview.WorkDescription'),
        ),
    ]
