# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=37.3004182, max_digits=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=-121.8761836, max_digits=10),
        ),
    ]
